---
editor_options: 
  markdown: 
    wrap: sentence
---

# Study Premise

Project MAXED (Phase 1: 2020-2024) is a study is conducting and investigation of exercise response among girls and young women with eating disorders developed by the EMBARK lab in 2020.

MAXED R21MH131787 (Phase 2: 2024- ) is being conducted at the University of California San Francisco (UCSF) and the University of Wisconsin-Madison and is a continuation of the MAXED study with a few protocol changes.

1.1 Specific Aims (MAXED):

Driven exercise is a serious and common feature of eating disorders, but current understanding of factors that give rise to and maintain driven exercise is limited.
Project MAXED aims to evaluate acute psychobiological response to a bout of moderate-intensity exercise among young females (age 14-22 years) with and without mild-to-moderate eating disorder symptoms.
Overall, this study will contribute to the conceptualization of driven exercise and how individuals’ acute biological and affective responses to exercise contribute to risk for and maintenance of driven exercise.
This pilot study has two primary aims:

Aim 1: Confirm feasibility of paradigms evaluating acute response to exercise among outpatient individuals with mild-to-moderate eating disorder symptoms.
We will confirm feasibility of our exercise-based tasks via a) study dropout at all timepoints, b) adverse events, c) completion rates of study tasks.
Over the course of the study, we expect both eating disorder and healthy control groups to meet thresholds of \< 20% dropout, zero adverse events, and \> 80% task completion.

Aim 2: Characterize variability in biobehavioral response to in-lab exercise among individuals with mild-to-moderate eating disorders.
We will characterize changes during exercise in state body image, mood, and biological markers in both eating disorder and healthy control groups; we will specifically characterize mean levels of, and variability in, biobehavioral response to exercise across the groups.

1.2 Specific Aims (MAXED R21MH131787):

This pilot R21 project will: 1) characterize variability in psychobiological response to in-lab moderate-intensity exercise among those with and without EDs; 2) create and refine exercise tasks that capture in-vivo exercise response; and 3) test the hypothesis that acute exercise response relates to DEx in those with EDs.
Our sample will include 67 female subjects (aged 16-22y) with a restrictive-spectrum ED diagnosis (AN; atypical AN; AN-spectrum OSFED) who are medically cleared for moderate-intensity exercise, along with 33 age-matched healthy controls (HC).
We will conduct a preliminary examination of multi-modal response (self-report, task-based learning, neurotransmitter shifts) to acute exercise using two novel tasks where subjects will: (Task 1) drink a high-calorie beverage prior to a self-paced bout of exercise to trigger threat and capture threat-reduction mechanisms of exercise, and (Task 2) engage in a prescribed, controlled bout of exercise to assess psychobiological exercise response.

Aim 1: Internal validation of in-lab exercise tasks: characterize variability in psychobiological response to in-lab exercise across ED and HC.
H1a: We expect improvements in both affect and body image during exercise, significant increases in cortisol, eCBs, BDNF, and significant decreases in leptin following moderate-intensity aerobic exercise, and no change in circulating biomarkers following the rest condition among those with EDs.
H1b: Individuals with EDs will exhibit stronger biomarker, body image (+), and affective (+) response to exercise as compared to HCs.
Exploratory: whether exercise impacts on learning differ across HC and ED.
H1c: Acute exercise response will evidence greater variability among those with EDs compared to HC.

Aim 2: External validation of in-lab acute exercise tasks: examine associations between acute exercise response and ED severity, self-reported DEx, and accelerometer-measured moderate-to-vigorous physical activity (MVPA) across ED and HCs.
H2: Findings will support concurrent validity of tasks.
Acute exercise response will positively associate with ED severity and DEx among those with EDs, and positively associate with free-living MVPA across ED and HCs.
Detailed explication of acute exercise effects among individuals with EDs in a controlled setting will (i) improve assessment of DEx risk and function among those with EDs, (ii) elucidate a testable model of DEx, and (iii) suggest targets for mechanistically informed DEx intervention
