# Interventions
There are 2 stages to this protocol: 1) Screening Day with screening assessments; and 2) Day A, DayB, and Day C that consist of computational and exercise tasks, questionnaires, and blood draw. Participants will complete these two stages across 4 separate days. Day A, Day B, and Day C will occur randomly, spaced 6-8 days apart. 

## Screening Day stage
During the Screening Day stage, participants will undergo a structured clinical interview to assess current eating disorder symptoms, psychological symptoms,cognitive function assessment, physical status, and demographics. If participants are under 18 years old, parents will also be asked to complete a demographics form. Participants will also complete the Approach Avoidance Conflict task. The assessment stage lasts 3-4 hours. 

## Day A, DayB, and Day C Stage
During Day A, participants will complete two different tasks–Task 1: “Reward task” (rest condition) will include self-report measures, two blood draws immediately before and after completing 30 minutes of rest to examine changes in key neurotransmitters over time, and a post-rest behavioral task; and Task 2: “Threat task”(active condition) will include self-report of state emotional, body image, behavioral urges and cravings,a food challenge task of drinking a milkshake, and 30 minutes of exercise. During Day B, participants will complete Task 1: Reward (active condition), that includes self-report questionnaires, a behavioral task in which participants will work to earn “points” for exercise, and two blood draws, including one immediately before and one immediately after completing the 30 minutes of exercise to examine changes in key neurotransmitters. On Day C, participants will complete Task 2: Threat (rest condition),which will include completion of self-report questionnaires, a food challenge task, and 30 minutes of rest. Participants will provide four blood samples total during this study. In order to ensure that blood monoamine and hormone levels are controlled, participants will be asked to refrain from eating after1:00pm, only eating a provided nutritional supplement (nutrition bar) as a snack before attending Day A and Day B study visits at 4pm. Additionally, Task Day B will be scheduled during the follicular phase to control for possible menstrual phase effects on the biological response to exercise. Menstrual phase will be further clarified and controlled by the collection of blood samples on Task Day B to quantify estradiol levels. Participants will also complete a reinforcement learning task following Day A and Day B to examine the acute impact of exercise on reinforcement learning mechanisms. Day A, Day B, and Day C will each last about 2 hours. Lastly, participants will be provided with a fitness tracker to wear for7 days between the screening visit and their second visit to objectively determine average levels of physical activity.
